public enum DungeonCrawlerType {
    PLAYER, ENEMY, SHOP, WEAPON, COIN, STAIRS, DOOR, HOLE, SPIKES, RIGHTWALL, LEFTWALL, TOPWALL, BOTTOMWALL, RIGHTVOID, LEFTVOID, BOTTOMVOID, TOPVOID, HPFOUNTAIN, MPFOUNTAIN, BUTTON, TRAP, RIGHTTRAPWALL, REDSWITCH, BLUESWITCH
}
