public enum DungeonCrawlerType {
    WALL, STAIRS, DOOR, HOLE, SPIKES, PLAYER, WEAPON, COIN, RIGHTWALL, LEFTWALL, TOPWALL, BOTTOMWALL, RIGHTVOID, LEFTVOID, BOTTOMVOID, TOPVOID, ENEMY, HPFOUNTAIN, MPFOUNTAIN, BUTTON, TRAP, RIGHTTRAPWALL, REDSWITCH, BLUESWITCH
}
